### ISSUE TITLE
How to get landmarks

### ISSUE THREAD

**Issue by PatrykKotlowski** [ZhiwenShao/PyTorch-JAANet#1]
Hello, 
Thank you very much for sharing your code!
I've got similar question I don't how to get face landmarks for all files. There is example for two images in BP4D_combine_1_2_land.txt file but I don't get how to get rest of them.

Thank you!

**Comment by ZhiwenShao** [comment]
You need to request the [BP4D](http://www.cs.binghamton.edu/~lijun/Research/3DFE/3DFE_Analysis.html) dataset, and process the landmark annotations to generate landmark files. I‘m sorry I can't share the landmark files due to the copyright issue.

**Comment by PatrykKotlowski** [comment]
Thank you very much form your answer
I’ve got access to BP4D. Am I right that landmarks are in the 2D Coding folder I’m not sure because I cannot find anything about landmarks in BP4D userguide

**Comment by ZhiwenShao** [comment]
My downloaded BP4D is a part of FERA 2015, and the landmark annotations are in the BP4D-fpoints folder. I guess the 2D Coding folder only contains AU annotations.

**Comment by rafikg** [comment]
Hello,
@ZhiwenShao How to visualize the predicted landmarks?

**Comment by liuliangchen1233-ux** [comment]
> Thank you very much form your answer I’ve got access to BP4D. Am I right that landmarks are in the 2D Coding folder I’m not sure because I cannot find anything about landmarks in BP4D userguide

Please send the dataset to me. Thank you very much! My email: 2024223045059@stu.scu.edu.cn
