### ISSUE TITLE
DISFA_combine_1_2_, 1_3, naming convention ?

### ISSUE THREAD

**Issue by rafikg** [ZhiwenShao/PyTorch-JAANet#12]
Hi,
Could you clarify what do you mean by `1_2, 1_3, ...`  naming convention?

**Comment by ZhiwenShao** [comment]
The experiments are conducted using 3-fold cross-validation. 1_2 means the training set contains the first and the second folds.

**Comment by rafikg** [comment]
@ZhiwenShao thanks!
