### ISSUE TITLE
The performance of BP4D dataset

### ISSUE THREAD

**Issue by gedaye11** [ZhiwenShao/PyTorch-JAANet#16]
Thanks for opening your great work.
Now,  we are reproducing your paper performance according to your readme to train JAANet-v2 model on the BP4D dataset, but we cannot get the results you said in the IJCV version. In BP4D-part3, we only get about F1-frame of 0.6 (decrease about 2.5%) .
This makes me very confused. 
Can you publish your pre-trained model on BP4D as you said?
Thanks

**Comment by ZhiwenShao** [comment]
The trained models can be downloaded [here](https://sjtueducn-my.sharepoint.com/:f:/g/personal/shaozhiwen_sjtu_edu_cn/Eu3SDFcZYG9Ah5RdRYqfYxoBWDyWici_FdWJP8TnYFqaZw?e=ogNmZv).
