### ISSUE TITLE
Could you provide the trained model?

### ISSUE THREAD

**Issue by ForrestPi** [ZhiwenShao/PyTorch-JAANet#17]

**Comment by ZhiwenShao** [comment]
Please see the ReadMe file. The trained models can be downloaded [here](https://sjtueducn-my.sharepoint.com/:f:/g/personal/shaozhiwen_sjtu_edu_cn/Eu3SDFcZYG9Ah5RdRYqfYxoBWDyWici_FdWJP8TnYFqaZw?e=ogNmZv).
