### ISSUE TITLE
DISFA_combine_1_2_weight.txt not found.

### ISSUE THREAD

**Issue by mahdidrm** [ZhiwenShao/PyTorch-JAANet#18]
Hello and thank you for sharing this code.
I downloaded the DISFA dataset and want to train and run your model with this dataset as you noted in the article.
I put the images as you said regarding the list path files. But in the pre-processing part, you noted:

Put the landmark annotation files into the folder "dataset".

In the DISFA dataset which I downloaded there are .Mat files as Landmarks. How should I use them?

Also i have the error "OSError: data/list/DISFA_combine_1_2_weight.txt not found."   which I dont know how I can get this file.

Can you guide me please?

Regards

**Comment by ZhiwenShao** [comment]
Please see the ReadMe file.
- Compute the weight of the loss of each AU for the training set:
  - The AU annoatation files should be in the folder "data/list"
  ```
  cd dataset
  python write_AU_weight.py
  ```

**Comment by mahdidrm** [comment]
Thank you very much for the reply.

Python write_AU_weight.py, write AU of BP4D dataset and make a file with name "BP4D_combine_1_2_weight.txt" not "DISFA_combine_1_2_weight.txt".. I should change the name of BP4D to DISFA or there is other file for do this?

**Comment by ZhiwenShao** [comment]
Yes, you should modify write_AU_weight.py for a new dataset such as DISFA.

**Comment by Taylaaa0807** [comment]
write_AU_weight.py中的BP4D_combine_1_2_AUoccur.txt文件是bp4d数据集自带的吗？没有bp4d这个数据集的话这份代码还能运行吗
