### ISSUE TITLE
Does the face_transform.py work for DISFA?

### ISSUE THREAD

**Issue by liupeiLu** [ZhiwenShao/PyTorch-JAANet#2]
Hello, It seems that the preprocess is implemented for BP4D dataset with 49 landmarks, but DISFA has 66 lankmarks. Will the face_transform.py works the same for 66 landmarks?
Thanks for the help!

**Comment by ZhiwenShao** [comment]
49 landmarks are a subset of 66 landmarks, so you can process the 66 landmarks to obtain 49 landmarks.

**Comment by liupeiLu** [comment]
Thanks for quick reply, could you please explain how to reduce from 66 to 49? like which lankmarks are removed?

**Comment by ZhiwenShao** [comment]
I have uploaded the read_disfa_49land.py into the folder "dataset". More details can be found in README.

**Comment by liupeiLu** [comment]
Thanks for the help!
