### ISSUE TITLE
DISFA AU_corr.txt template

### ISSUE THREAD

**Issue by gtallec** [ZhiwenShao/PyTorch-JAANet#20]
Hi,
Thank you for your work. Could you please provide template for AU annotation file on disfa (<your file template> + 'AU_occur.txt'). Especially the order of columns.
Thank you in advance.

**Comment by ZhiwenShao** [comment]
In the file of "dataset/write_AU_weight.py", there are comments for AU annotation template:

example of content in 'BP4D_combine_1_2_AUoccur.txt':
0 0 0 0 0 1 1 0 0 0 0 0
0 0 0 0 0 1 1 0 0 0 0 0
0 0 0 0 0 1 1 0 0 0 0 0

Each line denotes the annoations of $n$ AUs for one image, in which $n$ is the number of AUs.
