### ISSUE TITLE
'all_pred_land' negative value appears

### ISSUE THREAD

**Issue by YJLeonMan** [ZhiwenShao/PyTorch-JAANet#21]
Hi：
First of all, thank you for your sharing.
I have a problem:  When I run the test file  test_JAAv1.py,  'all_pred_land' negative value appears, but landmark it can't be negative

**Comment by ZhiwenShao** [comment]
There may be some errors with the training of landmark detection. It is suggested to check the landmark annotation file as well as related settings.
