### ISSUE TITLE
F1_Frame calculation

### ISSUE THREAD

**Issue by rafikg** [ZhiwenShao/PyTorch-JAANet#23]
Hi,
I am wondering how did you define `F1_frame`! `F1_score, precision and recall` can not be considered in this context because a lot of examples does not have a positive class

**Comment by ZhiwenShao** [comment]
F1_frame means frame-based F1 score, in which the implementation can be found in util.py. F1_frame of each AU is calculated over all the samples instead of only one sample.

**Comment by rafikg** [comment]
Hi @ZhiwenShao, If I understand correctly, it should be implemented as following:

```
import numpy as np
from sklearn.metrics import f1_score
def f1_frame(y_true, y_pred):
       """"
      y_true: N*8
      y_pred: N*8
      N is the number of frames
      examples: 3 frames
    
     y_true = np.array([[1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 1, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 1, 1]])
     y_pred = np.array([[1, 0, 0, 0, 1, 0, 0, 1], [1, 0, 0, 1, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 1, 0]])
       """"
    # Transpose `y_true` and `y_pred`
     y_true = np.transpose(y_true)
     y_pred = np.transpose(y_pred) 
      
     f1_score = f1_score(y_true, y_pred, average='weighted')
   
     return f1_score
```

**Comment by ZhiwenShao** [comment]
We need to compute f1 score of each AU independently, then compute the average f1 score over all the AUs. In your code, only one f1 score is computed and the result of each individual AU cannot be computed.

**Comment by rafikg** [comment]
@ZhiwenShao humm, you want to iterate over the AU as following:

```
import numpy as np
from sklearn.metrics import f1_score
def f1_frame(y_true, y_pred):
       """"
      y_true: N*8
      y_pred: N*8
      N is the number of frames
      examples: 3 frames
    
     y_true = np.array([[1, 0, 0, 0, 0, 0, 0, 1], [1, 0, 0, 1, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 1, 1]])
     y_pred = np.array([[1, 0, 0, 0, 1, 0, 0, 1], [1, 0, 0, 1, 0, 0, 0, 1], [1, 0, 0, 0, 0, 0, 1, 0]])
       """"
    # Transpose `y_true` and `y_pred`
     y_true = np.transpose(y_true)
     y_pred = np.transpose(y_pred) 
    f1_score_list = []
    for i in range(len(y_true)):
        f1_score = f1_score(y_true[i], y_pred[i], average='weighted')
        f1_score_list.append(f1_score)
   
     return np.mean(f1_score_list)



```

**Comment by ZhiwenShao** [comment]
No, over AUs instead of frames. See the util.py:
 
    AUoccur_actual = AUoccur_actual.transpose((1, 0))
    AUoccur_pred = AUoccur_pred.transpose((1, 0))

    f1score_arr = np.zeros(AUoccur_actual.shape[0])
    acc_arr = np.zeros(AUoccur_actual.shape[0])
    for i in range(AUoccur_actual.shape[0]):
        curr_actual = AUoccur_actual[i]
        curr_pred = AUoccur_pred[i]

        new_curr_actual = curr_actual[curr_actual != missing_label]
        new_curr_pred = curr_pred[curr_actual != missing_label]

        f1score_arr[i] = f1_score(new_curr_actual, new_curr_pred)
        acc_arr[i] = accuracy_score(new_curr_actual, new_curr_pred)

**Comment by rafikg** [comment]
Thanks @ZhiwenShao but  the only difference between your implementation and mine is the comparison with `missing_label=9` that I am not sure about the meaning. As you see I iterate over the Action unit not over frames in my code.
