### ISSUE TITLE
无法复现 DISFA 数据集的测试结果

### ISSUE THREAD

**Issue by Watebear** [ZhiwenShao/PyTorch-JAANet#24]
您好，感谢您的开源。我在DISFA数据集上用您提供的模型进行测试：
模型用的是: JAAV2/DISFA_combine_1_2, 测试列表是： DISFA_part3, 但测试的 平均 f1 仅有 0.519， 和论文差很多。

**Comment by ZhiwenShao** [comment]
Thanks very much for your interest. If the testing is conducted on the images preprocessed with our code, the results of our trained DISFA models (3-fold cross-validation) should be:

f1_score accuracy mean_error failure_rate
0.577556 0.929593 0.043427 0.000000
0.656207 0.939148 0.044319 0.000099
0.671716 0.950716 0.042331 0.000162

==============================
0.635159666666667 0.939819000000000 0.0433590000000000 8.70000000000000e-05

For more details, you can refer to this issue (https://github.com/ZhiwenShao/PyTorch-JAANet/issues/22).

**Comment by Watebear** [comment]
> hanks very much for your interest. If the testing is conducted on the images preprocessed with our code, the results of our trained DISFA models (3-fold cross-validation) should be
我检查了自己的代码，重新处理了一下数据，在 DISFA 上复现了您的结果。
我们学校在美国制裁名单上，BP4D数据集申请不到，想在GFT数据集上进行实验。请问您方便公开GFT的相关处理脚本和模型吗？我现在的工作是基于您的JAA做特征提取的，如果能得到模型，能节约不少时间。另外，GFT数据集可以在哪申请呢？

**Comment by 2383056591** [comment]
您好，感谢您的开源。我也在DISFA数据集上用您提供的模型进行了测试：
模型用的是: JAAV2/DISFA_combine_1_2, 测试列表是： DISFA_part3, 但测试的平均 f1和上述问题一样，也是 0.519， 想请问一下是预训练模型上传错误了还是怎么回事呢？

**Comment by ZhiwenShao** [comment]
I have again tested the uploaded models in DISFA_combine_1_2. The average f1 score is 0.577556. Note that we train and test only on Videos_LeftCamera of DISFA dataset.
