### ISSUE TITLE
Unable to configure DISFA as required

### ISSUE THREAD

**Issue by yuankaishen2001** [ZhiwenShao/PyTorch-JAANet#25]
Hi, 
I try to train the model on DISFA, but the DISFA database I applied for has only left and right view videos and no images. How can I deal with this?

**Comment by ZhiwenShao** [comment]
We only use the left-view videos, and extract images from the videos for training and testing.

**Comment by yuankaishen2001** [comment]
> 

OK! I get it! Thank you very much!
