### ISSUE TITLE
datasets help

### ISSUE THREAD

**Issue by xxzcool** [ZhiwenShao/PyTorch-JAANet#4]
Hello,
    Thank you for your great work!
    I want to run your codes for study, but i could not be able to download the BP4D and DISFA dataset, could you please send these two datasets to me. Thank you very very much!
    My email: zhonghongfa09@gmail.com

**Comment by liuliangchen1233-ux** [comment]
> Hello, Thank you for your great work! I want to run your codes for study, but i could not be able to download the BP4D and DISFA dataset, could you please send these two datasets to me. Thank you very very much! My email: [zhonghongfa09@gmail.com](mailto:zhonghongfa09@gmail.com)

Please send these two datasets to me,too. Thank you! My email: 2024223045059@stu.scu.edu.cn
