### ISSUE TITLE
Error in second iteration in training

### ISSUE THREAD

**Issue by PatrykKotlowski** [ZhiwenShao/PyTorch-JAANet#6]
Hello,
I've got issue with running code. I made all necessary preprocessing according to readme file. 
First iteration works just fine but in second one the following error occurs:

/home/patryk/.conda/envs/venv/lib/python3.8/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
**[epoch = 0][iter = 1][total_loss = inf][loss_au_softmax = 0.352187][loss_au_dice = 0.482275][loss_land = inf][loss_attention_refine = 8.406529]
learning rate = 0.010000 0.010000 0.020000 0.010000 0.010000 0.010000
the number of training iterations is 1**
Traceback (most recent call last):
  File "/home/patryk/git/PyTorch-JAANet/train_JAAv1.py", line 276, in <module>
    main(config)
  File "/home/patryk/git/PyTorch-JAANet/train_JAAv1.py", line 197, in main
    align_feat, align_output, aus_map = align_net(region_feat)
  File "/home/patryk/.conda/envs/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/patryk/git/PyTorch-JAANet/network.py", line 203, in forward
    generate_map(aus_map[i,0], self.crop_size, self.map_size+8, self.spatial_ratio, self.fill_coeff,
  File "/home/patryk/git/PyTorch-JAANet/network.py", line 166, in generate_map
    for h in range(int(start_h), int(end_h)+1):
ValueError: cannot convert float NaN to integer

Process finished with exit code 1

I debugged it and it turned out that first conv layer in **HierarchicalMultiScaleRegionLayer** produces array with all Nans. (73rd line in network.py file)

Have you any ideas what's wrong?

**Comment by ZhiwenShao** [comment]
please check whether you encounter the same [issue](https://github.com/ZhiwenShao/PyTorch-JAANet/issues/3).

**Comment by PatrykKotlowski** [comment]
Sorry you right! Sorry for wasting your time. :(

**Comment by ZhiwenShao** [comment]
It's ok~
