### ISSUE TITLE
Training on more FACS poses?

### ISSUE THREAD

**Issue by antithing** [ZhiwenShao/PyTorch-JAANet#7]
Hi, and thank you for making this code available.

I see that the BP4D dataset used has 7 FACS poses. Is it possible to use this code to train on more poses? I would like to use a 30 pose FACS set.

Obviously I would need to annotate my own data.

Also, how does the speed and accuracy compare to the caffe version?

Thanks again!

**Comment by ZhiwenShao** [comment]
Our paper also shows results on FERA 2017 with 9 poses, so you can directly use the code to train on multiple poses. The accuracy of PyTorch vesion is higher than Caffe vesion, in which the implementation differences can be found in README and Sec. 4.3.2 of our paper. Besides, the  PyTorch vesion is also faster.

**Comment by antithing** [comment]
Thank you! Once I have a model trained, when running this code on my own data, can I just pass an image straight in? Or do i need to provide a bounding box for the face as well? 

Do you have an example to load a single image and run inference?
Thank you very much!

**Comment by ZhiwenShao** [comment]
Of course you can train on your own data. Please see examples images in data/imgs/BP4D.
