### ISSUE TITLE
Getting output of AU Attention Refinement as image

### ISSUE THREAD

**Issue by PatrykKotlowski** [ZhiwenShao/PyTorch-JAANet#8]
Hello,
I was wondering is it possible to get output of "AU Attention Refinement" module and save it as image?  I was looking on your article and it seems to be possible because you included example image on net structure (Fig 3. - Green Image). 
I'm thinking about use this module as preprocessing to CONV LSTM network and see what happen.

**Comment by ZhiwenShao** [comment]
Of course. Please see README:
python test_JAAv1.py --run_name='JAAv1' --gpu_id=0 --pred_AU=False --vis_attention=True --start_epoch=5 --n_epochs=5 --test_path_prefix='data/list/BP4D_part3' --au_num=12

**Comment by PatrykKotlowski** [comment]
It works! Thank you
