### ISSUE TITLE
Problem regarding to BP4D_combine_1_2_AUoccur.txt

### ISSUE THREAD

**Issue by rainalexc** [ZhiwenShao/PyTorch-JAANet#9]
Hello and thank you for shared code. 
I am trying to run it on DISFA dataset (without BP4D) but I get an error according this file : BP4D_combine_1_2_AUoccur.txt which doesn't exist. Could you tell me what is this about and how can I solve it. The error is this :
  imgs_AUoccur = np.loadtxt(list_path_prefix + 'BP4D_combine_1_2_AUoccur.txt')

Thank you very much!

**Comment by ZhiwenShao** [comment]
Please refer to [README](https://github.com/ZhiwenShao/PyTorch-JAANet/blob/master/README.md). The dataset name is set via "--train_path_prefix".
